/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#define SWIG_FILE_WITH_INIT
#include "ffi_lib.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_FFIERROR_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  result = (ffierror)FFIERROR_OK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_FFIERROR_1NULL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  result = (ffierror)FFIERROR_NULL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_FFIERROR_1PANIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  result = (ffierror)FFIERROR_PANIC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_FFIERROR_1FAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  result = (ffierror)FFIERROR_FAIL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec2_1x_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  vec2 *arg1 = (vec2 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec2 **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec2_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  vec2 *arg1 = (vec2 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec2 **)&jarg1; 
  result = (float) ((arg1)->x);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec2_1y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  vec2 *arg1 = (vec2 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec2 **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec2_1y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  vec2 *arg1 = (vec2 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec2 **)&jarg1; 
  result = (float) ((arg1)->y);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_new_1vec2(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  vec2 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (vec2 *)new vec2();
  *(vec2 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_delete_1vec2(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  vec2 *arg1 = (vec2 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec2 **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec3_1x_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  vec3 *arg1 = (vec3 *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_vec3_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  result = (int) ((arg1)->x);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec3_1y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  vec3 *arg1 = (vec3 *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_vec3_1y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  result = (int) ((arg1)->y);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec3_1z_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  vec3 *arg1 = (vec3 *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_vec3_1z_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  result = (int) ((arg1)->z);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_new_1vec3(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  vec3 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (vec3 *)new vec3();
  *(vec3 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_delete_1vec3(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  vec3 *arg1 = (vec3 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec3 **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_my_1function(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  vec2 arg1 ;
  vec2 *argp1 ;
  vec2 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(vec2 **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null vec2");
    return 0;
  }
  arg1 = *argp1; 
  result = my_function(SWIG_STD_MOVE(arg1));
  *(vec2 **)&jresult = new vec2(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_vec3_1new(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  vec3 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (vec3 *)vec3_new(arg1,arg2,arg3);
  *(vec3 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (int)add(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_add_1reverse_1args(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  vec3 *arg4 = (vec3 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(vec3 **)&jarg4; 
  result = (int)add_reverse_args(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_dot(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  vec3 *arg2 = (vec3 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(vec3 **)&jarg1; 
  arg2 = *(vec3 **)&jarg2; 
  result = (int)dot(arg1,(vec3 const *)arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_cross(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  vec3 *arg2 = (vec3 *) 0 ;
  vec3 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(vec3 **)&jarg1; 
  arg2 = *(vec3 **)&jarg2; 
  result = cross(arg1,(vec3 const *)arg2);
  *(vec3 **)&jresult = new vec3(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_normalize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  vec3 *arg1 = (vec3 *) 0 ;
  vec3 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(vec3 **)&jarg1; 
  result = normalize(arg1);
  *(vec3 **)&jresult = new vec3(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_hello(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return ;
  }
  hello((char const *)arg1);
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
}


SWIGEXPORT jdouble JNICALL Java_com_example_ffi_1libJNI_benchmark_1rust(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)benchmark_rust();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_example_ffi_1libJNI_benchmark_1rust_1async(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)benchmark_rust_async();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_simple_1service_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  simpleservice **arg1 = (simpleservice **) 0 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(simpleservice ***)&jarg1; 
  result = (ffierror)simple_service_destroy(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_simple_1service_1new_1with(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  simpleservice **arg1 = (simpleservice **) 0 ;
  unsigned int arg2 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(simpleservice ***)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (ffierror)simple_service_new_with(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_vec4_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  vec4 **arg1 = (vec4 **) 0 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 ***)&jarg1; 
  result = (ffierror)vec4_destroy(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_example_ffi_1libJNI_vec4_1new(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5) {
  jint jresult = 0 ;
  vec4 **arg1 = (vec4 **) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  ffierror result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 ***)&jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  result = (ffierror)vec4_new(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec4_1dot(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jfloat jresult = 0 ;
  vec4 *arg1 = (vec4 *) 0 ;
  vec4 *arg2 = (vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  arg2 = *(vec4 **)&jarg2; 
  result = (float)vec4_dot((vec4 const *)arg1,(vec4 const *)arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec4_1get_1x(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  vec4 *arg1 = (vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  result = (float)vec4_get_x((vec4 const *)arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec4_1get_1y(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  vec4 *arg1 = (vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  result = (float)vec4_get_y((vec4 const *)arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec4_1get_1z(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  vec4 *arg1 = (vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  result = (float)vec4_get_z((vec4 const *)arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_vec4_1get_1w(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  vec4 *arg1 = (vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  result = (float)vec4_get_w((vec4 const *)arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec4_1set_1x(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  vec4 *arg1 = (vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  vec4_set_x(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec4_1set_1y(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  vec4 *arg1 = (vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  vec4_set_y(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec4_1set_1z(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  vec4 *arg1 = (vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  vec4_set_z(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_vec4_1set_1w(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  vec4 *arg1 = (vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  vec4_set_w(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_init_1logger(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  init_logger();
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_new_1SimpleService(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  SimpleService *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (SimpleService *)new SimpleService();
  *(SimpleService **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_delete_1SimpleService(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SimpleService *arg1 = (SimpleService *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SimpleService **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_SimpleService_1NewWith(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  SimpleService result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  result = SimpleService::NewWith(arg1);
  *(SimpleService **)&jresult = new SimpleService(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_SimpleService_1Dispose(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  SimpleService *arg1 = (SimpleService *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SimpleService **)&jarg1; 
  (arg1)->Dispose();
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_SimpleService_1Context(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  SimpleService *arg1 = (SimpleService *) 0 ;
  simpleservice *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SimpleService **)&jarg1; 
  result = (simpleservice *)((SimpleService const *)arg1)->Context();
  *(simpleservice **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_SimpleService_1FromContext(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  simpleservice *arg1 = (simpleservice *) 0 ;
  SimpleService result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(simpleservice **)&jarg1; 
  result = SimpleService::FromContext(arg1);
  *(SimpleService **)&jresult = new SimpleService(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_new_1Vec4(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Vec4 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Vec4 *)new Vec4();
  *(Vec4 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_delete_1Vec4(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Vec4 *arg1 = (Vec4 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Vec4 **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_Vec4_1New(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
  jlong jresult = 0 ;
  float arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  Vec4 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  result = Vec4::New(arg1,arg2,arg3,arg4);
  *(Vec4 **)&jresult = new Vec4(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_Vec4_1Dispose(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Vec4 *arg1 = (Vec4 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  (arg1)->Dispose();
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_Vec4_1Dot(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jfloat jresult = 0 ;
  Vec4 *arg1 = (Vec4 *) 0 ;
  vec4 *arg2 = (vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  arg2 = *(vec4 **)&jarg2; 
  result = (float)(arg1)->Dot((vec4 const *)arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_Vec4_1GetX(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vec4 *arg1 = (Vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  result = (float)(arg1)->GetX();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_Vec4_1GetY(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vec4 *arg1 = (Vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  result = (float)(arg1)->GetY();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_Vec4_1GetZ(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vec4 *arg1 = (Vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  result = (float)(arg1)->GetZ();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_example_ffi_1libJNI_Vec4_1GetW(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vec4 *arg1 = (Vec4 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  result = (float)(arg1)->GetW();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_Vec4_1SetX(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  Vec4 *arg1 = (Vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->SetX(arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_Vec4_1SetY(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  Vec4 *arg1 = (Vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->SetY(arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_Vec4_1SetZ(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  Vec4 *arg1 = (Vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->SetZ(arg2);
}


SWIGEXPORT void JNICALL Java_com_example_ffi_1libJNI_Vec4_1SetW(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  Vec4 *arg1 = (Vec4 *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->SetW(arg2);
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_Vec4_1Context(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Vec4 *arg1 = (Vec4 *) 0 ;
  vec4 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vec4 **)&jarg1; 
  result = (vec4 *)((Vec4 const *)arg1)->Context();
  *(vec4 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_ffi_1libJNI_Vec4_1FromContext(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  vec4 *arg1 = (vec4 *) 0 ;
  Vec4 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(vec4 **)&jarg1; 
  result = Vec4::FromContext(arg1);
  *(Vec4 **)&jresult = new Vec4(result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

