/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace ffi {
#endif // __cplusplus

typedef struct Vec3 {
  int32_t x;
  int32_t y;
  int32_t z;
} Vec3;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct Vec3 *vec3_new(int32_t x, int32_t y, int32_t z);

int32_t add(struct Vec3 *slf, int32_t x, int32_t y, int32_t z);

int32_t add_reverse_args(int32_t x, int32_t y, int32_t z, struct Vec3 *slf);

int32_t dot(struct Vec3 *slf, const struct Vec3 *other);

struct Vec3 cross(struct Vec3 *slf, const struct Vec3 *other);

struct Vec3 normalize(struct Vec3 *slf);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace ffi
#endif // __cplusplus
