/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example;

public class ffi_libJNI {
  public final static native int FFIERROR_OK_get();
  public final static native int FFIERROR_NULL_get();
  public final static native int FFIERROR_PANIC_get();
  public final static native int FFIERROR_FAIL_get();
  public final static native void vec2_x_set(long jarg1, vec2 jarg1_, float jarg2);
  public final static native float vec2_x_get(long jarg1, vec2 jarg1_);
  public final static native void vec2_y_set(long jarg1, vec2 jarg1_, float jarg2);
  public final static native float vec2_y_get(long jarg1, vec2 jarg1_);
  public final static native long new_vec2();
  public final static native void delete_vec2(long jarg1);
  public final static native void vec3_x_set(long jarg1, vec3 jarg1_, int jarg2);
  public final static native int vec3_x_get(long jarg1, vec3 jarg1_);
  public final static native void vec3_y_set(long jarg1, vec3 jarg1_, int jarg2);
  public final static native int vec3_y_get(long jarg1, vec3 jarg1_);
  public final static native void vec3_z_set(long jarg1, vec3 jarg1_, int jarg2);
  public final static native int vec3_z_get(long jarg1, vec3 jarg1_);
  public final static native long new_vec3();
  public final static native void delete_vec3(long jarg1);
  public final static native long my_function(long jarg1, vec2 jarg1_);
  public final static native long vec3_new(int jarg1, int jarg2, int jarg3);
  public final static native int add(long jarg1, vec3 jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native int add_reverse_args(int jarg1, int jarg2, int jarg3, long jarg4, vec3 jarg4_);
  public final static native int dot(long jarg1, vec3 jarg1_, long jarg2, vec3 jarg2_);
  public final static native long cross(long jarg1, vec3 jarg1_, long jarg2, vec3 jarg2_);
  public final static native long normalize(long jarg1, vec3 jarg1_);
  public final static native void hello(String jarg1);
  public final static native double benchmark_rust();
  public final static native double benchmark_rust_async();
  public final static native int simple_service_destroy(long jarg1);
  public final static native int simple_service_new_with(long jarg1, long jarg2);
  public final static native int vec4_destroy(long jarg1);
  public final static native int vec4_new(long jarg1, float jarg2, float jarg3, float jarg4, float jarg5);
  public final static native float vec4_dot(long jarg1, long jarg2);
  public final static native float vec4_get_x(long jarg1);
  public final static native float vec4_get_y(long jarg1);
  public final static native float vec4_get_z(long jarg1);
  public final static native float vec4_get_w(long jarg1);
  public final static native void vec4_set_x(long jarg1, float jarg2);
  public final static native void vec4_set_y(long jarg1, float jarg2);
  public final static native void vec4_set_z(long jarg1, float jarg2);
  public final static native void vec4_set_w(long jarg1, float jarg2);
  public final static native void init_logger();
  public final static native long new_SimpleService();
  public final static native void delete_SimpleService(long jarg1);
  public final static native long SimpleService_NewWith(long jarg1);
  public final static native void SimpleService_Dispose(long jarg1, SimpleService jarg1_);
  public final static native long SimpleService_Context(long jarg1, SimpleService jarg1_);
  public final static native long SimpleService_FromContext(long jarg1);
  public final static native long new_Vec4();
  public final static native void delete_Vec4(long jarg1);
  public final static native long Vec4_New(float jarg1, float jarg2, float jarg3, float jarg4);
  public final static native void Vec4_Dispose(long jarg1, Vec4 jarg1_);
  public final static native float Vec4_Dot(long jarg1, Vec4 jarg1_, long jarg2);
  public final static native float Vec4_GetX(long jarg1, Vec4 jarg1_);
  public final static native float Vec4_GetY(long jarg1, Vec4 jarg1_);
  public final static native float Vec4_GetZ(long jarg1, Vec4 jarg1_);
  public final static native float Vec4_GetW(long jarg1, Vec4 jarg1_);
  public final static native void Vec4_SetX(long jarg1, Vec4 jarg1_, float jarg2);
  public final static native void Vec4_SetY(long jarg1, Vec4 jarg1_, float jarg2);
  public final static native void Vec4_SetZ(long jarg1, Vec4 jarg1_, float jarg2);
  public final static native void Vec4_SetW(long jarg1, Vec4 jarg1_, float jarg2);
  public final static native long Vec4_Context(long jarg1, Vec4 jarg1_);
  public final static native long Vec4_FromContext(long jarg1);
}
