/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example;

public final class ffierror {
  public final static ffierror FFIERROR_OK = new ffierror("FFIERROR_OK", ffi_libJNI.FFIERROR_OK_get());
  public final static ffierror FFIERROR_NULL = new ffierror("FFIERROR_NULL", ffi_libJNI.FFIERROR_NULL_get());
  public final static ffierror FFIERROR_PANIC = new ffierror("FFIERROR_PANIC", ffi_libJNI.FFIERROR_PANIC_get());
  public final static ffierror FFIERROR_FAIL = new ffierror("FFIERROR_FAIL", ffi_libJNI.FFIERROR_FAIL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ffierror swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ffierror.class + " with value " + swigValue);
  }

  private ffierror(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ffierror(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ffierror(String swigName, ffierror swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ffierror[] swigValues = { FFIERROR_OK, FFIERROR_NULL, FFIERROR_PANIC, FFIERROR_FAIL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

