/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example;

public class vec3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vec3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vec3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(vec3 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffi_libJNI.delete_vec3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(SWIGTYPE_p_int32_t value) {
    ffi_libJNI.vec3_x_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getX() {
    return new SWIGTYPE_p_int32_t(ffi_libJNI.vec3_x_get(swigCPtr, this), true);
  }

  public void setY(SWIGTYPE_p_int32_t value) {
    ffi_libJNI.vec3_y_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getY() {
    return new SWIGTYPE_p_int32_t(ffi_libJNI.vec3_y_get(swigCPtr, this), true);
  }

  public void setZ(SWIGTYPE_p_int32_t value) {
    ffi_libJNI.vec3_z_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getZ() {
    return new SWIGTYPE_p_int32_t(ffi_libJNI.vec3_z_get(swigCPtr, this), true);
  }

  public vec3() {
    this(ffi_libJNI.new_vec3(), true);
  }

}
